### PR TITLE
fixed zoom bug

### PR DESCRIPTION
**Pull request by QingWei-Li**

### CODE REVIEW

**Comment by cburgmer** [comment]
Hey, thanks for the change. There's a bit more we need to do though:

After your change, the integration tests are failing for Firefox now. You should be able to reproduce it easily:

Run the following on the command line
```
$ python -m SimpleHTTPServer
```

and open `http://localhost:8000/test/manualIntegrationTestForWebkit.html` in the browser. While Chrome is still looking good, the last three images are broken in Firefox.

Can you provide a simple example to show how the zoom is failing? I'll might be able to help out. Also after we fix the issue, we should provide a test using the failing example to make sure it doesn't fail again in the future.

**Comment by QingWei-Li** [comment]
hey, cburgmer
My issue like is https://jsfiddle.net/cinwell_li/z1kxmrnn/1/
In chrome and FF, the result is different. the `box ` element is 50px 50px size in chrome, is 100px 100px size in firefox.

When element is relative position and set zoom, the issue is happened.

**Comment by cburgmer** [comment]
Thanks, I'll have a more detailed look with a bit more time. 

I think the issue with your latest change is that the zoom parameter is tightly coupled to width/height and x/y parameter. The assumption so far has been that the transform happens on the same element. 

Those values are calculated in `calculateContentSize()` in `browser.js`. Changing the parameter placement might need changing this calculation.

**Comment by cburgmer** [comment]
Hey, I've been thinking a bit about where this issue is coming from. If we truly understood what is going wrong, the fix would probably be fairly simple. However, I currently do not understand why Chrome decides to render the example differently to Firefox. I am hesitant to implement a workaround until we understand if it is either a fault on our side, or a bug in Chrome. For the latter we should raise an issue with Chrome (while we could still add a workaround).

For further debugging, I've simplified your example down to "just" SVG code, so we can reason about the issue without any code in rasterizeHTML.js: http://jsfiddle.net/cburgmer/o7sgq4oe/

Just wanted to let you know that I haven't forgotten about you :)

**Comment by QingWei-Li** [comment]
Hi!
In safari also has the same issue. so I think this is bug in webkit (maybe?).

**Comment by cburgmer** [comment]
Yes, Chrome and Safari are still pretty close in behaviour and issues.

What I'll try to see is wether we can experience a similar behaviour when using non-SVG tags, with the same styling setup.

**Comment by cburgmer** [comment]
Hey, it turns out there was just a minor thing lacking to make Firefox happy with your change.

I still don't understand the issue Chrome/Safari are facing, it might make sense to open a bug report with them.

**Comment by cburgmer** [comment]
Thanks for the fix!

**Comment by QingWei-Li** [comment]
:-P

**Pull request merged**
